version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hypervest-postgres
    environment:
      POSTGRES_USER: hypervest
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: hypervest_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: hypervest-redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: 